---

-
 # User Creation: without Comment
  # Target:
  hosts: linux
  
  # Task:
  tasks:
    - name: Creating User, to view! ssh root@10.0.3.218 tail -5 /etc/passwd   ****
      user:
        name: "{{item}}"
        state: absent         # Once created enable to to Delete them!    ******** 
      with_items:
        - Brad
        - DeCaprio
        - Bale
        - Tom

...  
