---
#  User Creation with Dict within Dict as Loop within Loop, Subelement expects a list
- 
  # Target: where our play will run and options it will run with
  hosts: linux
 
  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Creating user using Loop within Loop, To view! ssh AND to delete Ref Playbook!!!! 
      user:
        name: "{{ item.1 }}"
        comment: "{{ item.1 | title }} {{ item.0.surname }}"
      with_subelements: 
        - family:
            surname: Spurin
            members:
             - leah
             - hayley
             - lily
             - anwen
        - members

# Three dots indicate the end of a YAML document
...

