---

# 

-

  # Target:
  hosts: linux

  # Task:
  tasks:
    - name: Exploring register
      command: hostname -s
      register: hostname_output
    
    - name: This Section Shows hostname_output
      debug:
        var: hostname_output
    
    - name: Shows hostname_output STD
      debug:
        var: hostname_output.stdout
    
    - name: Shows hostname_output STD
      debug:
        var: hostname_output.start

# Three dots indicate the end of a YAML document
...

